# Generated by Django 5.2 on 2025-04-27 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pauses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pause',
            name='pause_type',
        ),
        migrations.AddField(
            model_name='pause',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pause',
            name='type_of_pause',
            field=models.CharField(choices=[('Café', 'Café'), ('Déjeuner', 'Déjeuner')], default='Café', max_length=20),
        ),
        migrations.AlterField(
            model_name='pause',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
